[[main]]
    identifier = "bio"
    name = "Bio"
    url = "/"
    weight = 1

[[main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 2
    
[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 3

[[main]]
    identifier = "draws"
    name = "Draws"
    url = "/draws"
    weight = 5

[[main]]
    identifier = "extras"
    name = "Extras"
    url = "/extras"
    weight = 5

[[main]]
    identifier = "tutoring"
    name = "Tutoring"
    url = "/tutoring"
    weight = 6

